### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by mahdi4k** [alibaba-aero/vuilerplate#35]
When trying to install the npm packages using npm i command, I am getting the following exception:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vuilerplate@0.0.3
npm ERR! Found: happy-dom@6.0.2
npm ERR! node_modules/happy-dom
npm ERR!   dev happy-dom@"6.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer happy-dom@"^5.3.1" from vite-plugin-md@0.18.1
npm ERR! node_modules/vite-plugin-md
npm ERR!   dev vite-plugin-md@"^0.18.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\bistun\AppData\Local\npm-cache\eresolve-report.txt for a full report.

When I run  npm install --legacy-peer-deps
npm ERR! code 1
npm ERR! path C:\...
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'lodash'
npm ERR! Require stack:

**Comment by Hossein-Mirazimi** [comment]
you must install dependencies by pnpm i
because this repository use pnpm

**Comment by hossein13m** [comment]
I think it is safe to close this issue @mHooshdar
